[package]
name = "web-macros"
version = { workspace = true }
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
